language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - DB=mysql
  - DB=sqlite

services:
  - mysql

before_script:
  - composer install
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS mp_test;'; fi"

script: DB=travis/$DB vendor/bin/phpunit --debug
