language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=mysql
  - DB=sqlite

before_script:
  - composer install
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS mp_test;'; fi"

script: DB=travis/$DB phpunit --debug
