language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - DB=mysql
  - DB=sqlite

services:
  - mysql

before_script:
  - composer install
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS mp_test;'; fi"

script: DB=travis/$DB vendor/bin/phpunit --debug
