<?php
/**
 * @author CONTENT CONTROL http://www.contentcontrol-berlin.de/
 * @copyright CONTENT CONTROL http://www.contentcontrol-berlin.de/
 * @license http://www.gnu.org/licenses/gpl.html GNU General Public License
 */
namespace midgard\portable\api;

/**
 * @todo These properties should be autogenerated from XML
 *
 * @property string $creator
 * @property \midgard_datetime $created
 * @property string $revisor"
 * @property \midgard_datetime $revised
 * @property integer $revision
 * @property string $locker
 * @property \midgard_datetime $locked
 * @property string $approver
 * @property \midgard_datetime $approved
 * @property string $authors
 * @property string $owner
 * @property \midgard_datetime $schedulestart
 * @property \midgard_datetime $scheduleend
 * @property boolean $hidden
 * @property boolean $navnoentry
 * @property integer $size
 * @property \midgard_datetime $published
 * @property integer $score
 * @property \midgard_datetime $imported
 * @property \midgard_datetime $exported
 * @property boolean $deleted
 * @property boolean $islocked
 * @property boolean $isapproved
 */
class metadata
{
    private mgdobject $object;

    public function __construct(mgdobject $object)
    {
        $this->object = $object;
    }

    public function __get($property)
    {
        return $this->object->{'metadata_' . $property};
    }

    public function __set($property, $value)
    {
        //TODO: filter out readonly properties (?)
        $this->object->{'metadata_' . $property} = $value;
    }

    public function __isset($field)
    {
        return property_exists($this->object, 'metadata_' . $field);
    }
}
