name: PHPUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: Ubuntu-20.04
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mp_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    env:
      extensions: intl,memcached,apcu

    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']
        db: ['mysql', 'sqlite']
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: "none"
        ini-values: date.timezone=Europe/Berlin
        php-version: "${{ matrix.php-versions }}"
        extensions: "${{ env.extensions }}"

    - name: Start MySQL service
      if: "${{ matrix.db == 'mysql' }}"
      run: |
        mysql --host=localhost --port=${{ job.services.mysql.ports[3306] }} --protocol=TCP -u root -e 'create database IF NOT EXISTS mp_test;'
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-versions }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: vendor/bin/phpunit
      env: 
        DB: travis/${{ matrix.db }}
        MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
